data-module: experiment.qa.data.insuranceqa.v2
model-module: experiment.qa_hinge.model.lw_paper.cnn
training-module: experiment.qa_hinge.train.training
evaluation-module: experiment.qa_hinge.evaluation.evaluation

logger:
  level: DEBUG
  path: logs/insuranceqa_cnn.txt

global:
  question_length: 56
  answer_length: 200
  embedding_size: 300

data:
  lowercased: true
  map_oov: true
  map_numbers: false
  embeddings_path: data/glove.840B.300d.txt

  insuranceqa: data/insuranceQA

model:
  filters: 400
  filter_size: 3
  trainable_embeddings: false
  margin: 0.2

training:
  n_train_answers: 50
  save_folder: checkpoints/insuranceqa_cnn
  remove_save_folder_on_start: false
  epochs: 50
  early_stopping_patience: 10
  dropout: 0.3

  optimizer: adam
  initial_learning_rate: 0.0004
  dynamic_learning_rate: false

  scorer: accuracy
  scorer_print:
    - map
    - mrr

  batchsize: 20
  batchsize_valid: 512

evaluation:
  skip: false