data-module: experiment.qa.data.insuranceqa.tsv
model-module: experiment.qa_hinge.model.lw_paper.cnn
training-module: experiment.qa_hinge.train.training
evaluation-module: experiment.qa_hinge.evaluation.evaluation

logger:
  level: DEBUG
  path: logs/se_cooking_cnn.txt

global:
  question_length: 50
  answer_length: 400
  embedding_size: 300

data:
  lowercased: false
  map_oov: true
  map_numbers: false
  embeddings_path: data/glove.840B.300d.txt

  train_data:
    - data/stackexchange-answerselection/cooking.stackexchange.com

model:
  filters: 920
  filter_size: 3
  trainable_embeddings: false
  margin: 0.2

training:
  n_train_answers: 50
  save_folder: checkpoints/se_cooking_cnn
  remove_save_folder_on_start: false
  epochs: 50
  early_stopping_patience: 10
  dropout: 0.1

  optimizer: adam
  initial_learning_rate: 0.0001
  dynamic_learning_rate: false

  scorer: accuracy
  scorer_print:
    - map
    - mrr

  batchsize: 30
  batchsize_valid: 512

evaluation:
  skip: false
